{
    'contributors': None,
    'truncated': False,
    'text': '@intwentyfifteen this is a reply to a tweet',
    'in_reply_to_status_id': 550118735629934592,
    'id': 550339099429584898,
    'favorite_count': 0,
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'retweeted': False,
    'coordinates': None,
    'timestamp_ms': '1420046040767',
    'entities': {
        'symbols': [],
        'user_mentions': [{
            'id': 2951110814,
            'indices': [0, 16],
            'id_str': '2951110814',
            'screen_name': 'intwentyfifteen',
            'name': 'Best Intentions'
        }],
        'hashtags': [],
        'urls': []
    },
    'in_reply_to_screen_name': 'intwentyfifteen',
    'id_str': '550339099429584898',
    'retweet_count': 0,
    'in_reply_to_user_id': 2951110814,
    'favorited': False,
    'user': {
        'follow_request_sent': None,
        'profile_use_background_image': True,
        'default_profile_image': True,
        'id': 2929103956,
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'verified': False,
        'profile_location': None,
        'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
        'profile_sidebar_fill_color': 'DDEEF6',
        'profile_text_color': '333333',
        'followers_count': 2,
        'profile_sidebar_border_color': 'C0DEED',
        'id_str': '2929103956',
        'profile_background_color': 'C0DEED',
        'listed_count': 0,
        'is_translation_enabled': False,
        'utc_offset': None,
        'statuses_count': 20,
        'description': None,
        'friends_count': 2,
        'location': '',
        'profile_link_color': '0084B4',
        'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
        'following': None,
        'geo_enabled': False,
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'name': 'Test Bot',
        'lang': 'en',
        'profile_background_tile': False,
        'favourites_count': 0,
        'screen_name': 'testbottammy',
        'notifications': None,
        'url': None,
        'created_at': 'Thu Dec 18 06:03:47 +0000 2014',
        'contributors_enabled': False,
        'time_zone': None,
        'protected': False,
        'default_profile': True,
        'is_translator': False
    },
    'geo': None,
    'in_reply_to_user_id_str': '2951110814',
    'lang': 'en',
    'created_at': 'Wed Dec 31 17:14:00 +0000 2014',
    'filter_level': 'medium',
    'in_reply_to_status_id_str': '550118735629934592',
    'place': None
}
