{
    'contributors': None,
    'truncated': False,
    'text': '@intwentyfifteen this is a reply to a user',
    'in_reply_to_status_id': None,
    'id': 550339266744565760,
    'favorite_count': 0,
    'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    'retweeted': False,
    'coordinates': None,
    'timestamp_ms': '1420046080658',
    'entities': {
        'symbols': [],
        'user_mentions': [{
            'id': 2951110814,
            'indices': [0, 16],
            'id_str': '2951110814',
            'screen_name': 'intwentyfifteen',
            'name': 'Best Intentions'
        }],
        'hashtags': [],
        'urls': []
    },
    'in_reply_to_screen_name': 'intwentyfifteen',
    'id_str': '550339266744565760',
    'retweet_count': 0,
    'in_reply_to_user_id': 2951110814,
    'favorited': False,
    'user': {
        'follow_request_sent': None,
        'profile_use_background_image': True,
        'default_profile_image': False,
        'id': 24398192,
        'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png',
        'verified': False,
        'profile_location': None,
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/547672721610379265/As7r9J1N_normal.png',
        'profile_sidebar_fill_color': '252429',
        'profile_text_color': '666666',
        'followers_count': 429,
        'profile_sidebar_border_color': 'FFFFFF',
        'id_str': '24398192',
        'profile_background_color': '1A1B1F',
        'listed_count': 12,
        'is_translation_enabled': False,
        'utc_offset': -18000,
        'statuses_count': 2142,
        'description': 'developer, biker, midwesterner, bot-er.                                 http://52bots.tumblr.com // #botALLY',
        'friends_count': 544,
        'location': 'Los Angeles, CA',
        'profile_link_color': '2FC2EF',
        'profile_image_url': 'http://pbs.twimg.com/profile_images/547672721610379265/As7r9J1N_normal.png',
        'following': None,
        'geo_enabled': True,
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/24398192/1393448193',
        'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png',
        'name': 'christa',
        'lang': 'en',
        'profile_background_tile': True,
        'favourites_count': 1038,
        'screen_name': '_hartsick',
        'notifications': None,
        'url': 'http://chartsock.com',
        'created_at': 'Sat Mar 14 17:20:57 +0000 2009',
        'contributors_enabled': False,
        'time_zone': 'Eastern Time (US & Canada)',
        'protected': False,
        'default_profile': False,
        'is_translator': False
    },
    'geo': None,
    'in_reply_to_user_id_str': '2951110814',
    'lang': 'en',
    'created_at': 'Wed Dec 31 17:14:40 +0000 2014',
    'filter_level': 'medium',
    'in_reply_to_status_id_str': None,
    'place': None
}
