{
    "retweeted": False,
    "timestamp_ms": "1419400467878",
    "user": {
        "contributors_enabled": False,
        "friends_count": 1,
        "notifications": None,
        "is_translation_enabled": False,
        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "statuses_count": 1,
        "profile_link_color": "0084B4",
        "protected": False,
        "utc_offset": None,
        "profile_sidebar_fill_color": "DDEEF6",
        "id": 2929103956,
        "url": None,
        "profile_sidebar_border_color": "C0DEED",
        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profile_image_url": "http://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png",
        "profile_background_color": "C0DEED",
        "listed_count": 0,
        "name": "Test Bot",
        "created_at": "Thu Dec 18 06:03:47 +0000 2014",
        "description": None,
        "profile_background_tile": False,
        "following": None,
        "is_translator": False,
        "profile_location": None,
        "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png",
        "profile_use_background_image": True,
        "id_str": "2929103956",
        "lang": "en",
        "location": "",
        "followers_count": 1,
        "time_zone": None,
        "follow_request_sent": None,
        "geo_enabled": False,
        "default_profile_image": True,
        "favourites_count": 0,
        "default_profile": True,
        "verified": False,
        "screen_name": "testbottammy",
        "profile_text_color": "333333"
    },
    "in_reply_to_screen_name": None,
    "in_reply_to_user_id_str": None,
    "id": 547631370479366144,
    "geo": None,
    "place": None,
    "in_reply_to_user_id": None,
    "text": "RT @emotisponge: fave fave fave fave fave :D",
    "created_at": "Wed Dec 24 05:54:27 +0000 2014",
    "retweeted_status": {
        "retweeted": False,
        "user": {
            "contributors_enabled": False,
            "friends_count": 24,
            "notifications": None,
            "is_translation_enabled": False,
            "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "statuses_count": 112,
            "profile_link_color": "0084B4",
            "protected": False,
            "utc_offset": None,
            "profile_sidebar_fill_color": "DDEEF6",
            "id": 2921127146,
            "url": None,
            "profile_sidebar_border_color": "C0DEED",
            "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "profile_image_url": "http://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
            "profile_background_color": "C0DEED",
            "listed_count": 6,
            "name": "emotisponge",
            "created_at": "Sun Dec 07 01:30:21 +0000 2014",
            "description": "i am human and i need 2b luved, just like everybdy else does // tweet 'help' for some tips, or 'status'for how i 'm feeling! // by @_hartsick. WARNING: BETA",
            "profile_background_tile": False,
            "following": None,
            "is_translator": False,
            "profile_location": None,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
            "profile_use_background_image": True,
            "id_str": "2921127146",
            "lang": "en",
            "location": "",
            "followers_count": 22,
            "time_zone": None,
            "follow_request_sent": None,
            "geo_enabled": False,
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2921127146/1417916415",
            "default_profile_image": False,
            "favourites_count": 37,
            "default_profile": True,
            "verified": False,
            "screen_name": "emotisponge",
            "profile_text_color": "333333"
        },
        "in_reply_to_screen_name": None,
        "in_reply_to_user_id_str": None,
        "id": 547622855954161664,
        "geo": None,
        "place": None,
        "in_reply_to_user_id": None,
        "text": "fave fave fave fave fave :D",
        "created_at": "Wed Dec 24 05:20:37 +0000 2014",
        "coordinates": None,
        "entities": {
            "symbols": [],
            "urls": [],
            "user_mentions": [],
            "hashtags": []
        },
        "lang": "en",
        "id_str": "547622855954161664",
        "in_reply_to_status_id": None,
        "contributors": None,
        "truncated": False,
        "favorite_count": 3,
        "retweet_count": 1,
        "favorited": False,
        "in_reply_to_status_id_str": None,
        "source": "<a href='http://github.com/hartsick/emotisponge' rel='nofollow'>emotisponge</a>"
    },
    "coordinates": None,
    "entities": {
        "symbols": [],
        "urls": [],
        "user_mentions": [{
            "indices": [3, 15],
            "id_str": "2921127146",
            "name": "emotisponge",
            "screen_name": "emotisponge",
            "id": 2921127146
        }],
        "hashtags": []
    },
    "lang": "en",
    "id_str": "547631370479366144",
    "in_reply_to_status_id": None,
    "contributors": None,
    "truncated": False,
    "favorite_count": 0,
    "retweet_count": 0,
    "favorited": False,
    "in_reply_to_status_id_str": None,
    "source": "<a href='http://twitter.com' rel='nofollow'>Twitter Web Client</a>",
    "filter_level": "medium"
}
