{
    "direct_message": {
        "id_str": "545466373041029120",
        "text": "sfasf",
        "recipient": {
            "profile_text_color": "333333",
            "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "name": "emotisponge",
            "verified": False,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
            "following": False,
            "notifications": False,
            "created_at": "Sun Dec 07 01:30:21 +0000 2014",
            "default_profile": True,
            "follow_request_sent": False,
            "is_translation_enabled": False,
            "lang": "en",
            "profile_sidebar_border_color": "C0DEED",
            "is_translator": False,
            "profile_use_background_image": True,
            "listed_count": 5,
            "profile_sidebar_fill_color": "DDEEF6",
            "geo_enabled": False,
            "friends_count": 23,
            "id": 2921127146,
            "profile_image_url": "http://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
            "profile_link_color": "0084B4",
            "profile_background_tile": False,
            "favourites_count": 27,
            "utc_offset": None,
            "screen_name": "emotisponge",
            "description": "i am human and i need 2b luved, just like everybdy else does // tweet 'help' for some tips, or 'status' for how i'm feeling! // by @_hartsick. WARNING: BETA",
            "time_zone": None,
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2921127146/1417916415",
            "profile_location": None,
            "id_str": "2921127146",
            "statuses_count": 89,
            "default_profile_image": False,
            "profile_background_color": "C0DEED",
            "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "location": None,
            "protected": False,
            "followers_count": 21,
            "contributors_enabled": False,
            "url": None
        },
        "recipient_screen_name": "emotisponge",
        "created_at": "Thu Dec 18 06:31:32 +0000 2014",
        "id": 545466373041029120,
        "sender_id_str": "2929103956",
        "recipient_id_str": "2921127146",
        "sender_screen_name": "testbottammy",
        "sender": {
            "profile_text_color": "333333",
            "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "name": "Test Bot",
            "verified": False,
            "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png",
            "following": False,
            "notifications": False,
            "created_at": "Thu Dec 18 06:03:47 +0000 2014",
            "default_profile": True,
            "follow_request_sent": False,
            "is_translation_enabled": False,
            "lang": "en",
            "profile_sidebar_border_color": "C0DEED",
            "is_translator": False,
            "profile_use_background_image": True,
            "listed_count": 0,
            "profile_sidebar_fill_color": "DDEEF6",
            "geo_enabled": False,
            "friends_count": 1,
            "id": 2929103956,
            "profile_image_url": "http://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png",
            "profile_link_color": "0084B4",
            "profile_background_tile": False,
            "favourites_count": 0,
            "utc_offset": None,
            "screen_name": "testbottammy",
            "description": None,
            "time_zone": None,
            "profile_location": None,
            "id_str": "2929103956",
            "statuses_count": 0,
            "default_profile_image": True,
            "profile_background_color": "C0DEED",
            "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "location": None,
            "protected": False,
            "followers_count": 1,
            "contributors_enabled": False,
            "url": None
        },
        "entities": {
            "urls": [],
            "symbols": [],
            "hashtags": [],
            "user_mentions": []
        },
        "recipient_id": 2921127146,
        "sender_id": 2929103956
    }
}
