{
    "target": {
        "contributors_enabled": False,
        "friends_count": 24,
        "notifications": None,
        "is_translation_enabled": False,
        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "statuses_count": 102,
        "profile_link_color": "0084B4",
        "protected": False,
        "utc_offset": None,
        "profile_sidebar_fill_color": "DDEEF6",
        "id": 2921127146,
        "url": None,
        "profile_sidebar_border_color": "C0DEED",
        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profile_image_url": "http://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
        "profile_background_color": "C0DEED",
        "listed_count": 6,
        "name": "emotisponge",
        "created_at": "Sun Dec 07 01:30:21 +0000 2014",
        "description": "i am human and i need 2b luved, just like everybdy else does // tweet 'help' for some tips, or 'status' for how i'm feeling! // by @_hartsick. WARNING: BETA",
        "profile_background_tile": False,
        "following": None,
        "is_translator": False,
        "profile_location": None,
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
        "profile_use_background_image": True,
        "id_str": "2921127146",
        "lang": "en",
        "location": None,
        "followers_count": 22,
        "time_zone": None,
        "follow_request_sent": None,
        "geo_enabled": False,
        "profile_banner_url": "https://pbs.twimg.com/profile_banners/2921127146/1417916415",
        "default_profi
        le_image ": False,
        "favourites_count": 30,
        "default_profile": True,
        "verified": False,
        "screen_name": "emotisponge",
        "profile_text_color": "333333"
    },
    "event": "favorited_retweet",
    "target_object": {
        "retweeted": False,
        "user": {
            "contributors_enabled": False,
            "friends_count": 24,
            "notifications": None,
            "is_translation_enabled": False,
            "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
            "statuses_count": 102,
            "profile_link_color": "0084B4",
            "protected": False,
            "utc_offset": None,
            "profile_sidebar_fill_color": "DDEEF6",
            "id": 2921127146,
            "url": None,
            "profile_sidebar_border_color": "C0DEED",
            "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
            "profile_image_url": "http://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
            "profile_background_color": "C0DEED",
            "listed_count": 6,
            "name": "emotisponge",
            "created_at": "Sun Dec 07 01:30:21 +0000 2014",
            "description": "i am human and i need 2b luved, just like everybdy else does // tweet 'help' for some tips, or 'status' for how i'm feeling! // by @_hartsick. WARNING: BETA",
            "profile_background_tile": False,
            "following": None,
            "is_translator": False,
            "profile_location": None,
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
            "profile_use_background_image": True,
            "id_str": "2921127146",
            "lang": "en",
            "location": None,
            "followers_count": 22,
            "time_zone": None,
            "follow_request_sent": None,
            "geo_enabled": False,
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/2921127146/1417916415",
            "default_profile_image": False,
            "favourites_count": 30,
            "default_profile": True,
            "verified": False,
            "screen_name": "emotisponge",
            "profile_text_color": "333333"
        },
        "in_reply_to_screen_name": None,
        "in_reply_to_user_id_str": None,
        "id": 544653483082006528,
        "geo": None,
        "place": None,
        "in_reply_to_user_id": None,
        "text": u "RT @inky: @emotisponge you make me sick\u2026 with happiness",
        "created_at": "Tue Dec 16 00:41:24 +0000 2014",
        "coordinates": None,
        "entities": {
            "symbols": [],
            "urls": [],
            "user_mentions": [{
                "indices": [3, 8],
                "id_str": "13148",
                "name": u "LI\u039bM\u2008\u2746",
                "screen_name": "inky",
                "id": 13148
            },
            {
                "indices": [10, 22],
                "id_str": "2921127146",
                "name": "emotisponge",
                "screen_name": "emotisponge",
                "id": 2921127146
            }],
            "hashtags": []
        },
        "lang": "en",
        "id_str": "544653483082006528",
        "in_reply_to_status_id": None,
        "contributors": None,
        "truncated": False,
        "favorite_count": 0,
        "retweet_count": 0,
        "favorited": False,
        "in_reply_to_status_id_str": None,
        "source": "<a href='http://github.com/hartsick/emotisponge' rel='nofollow'>emotisponge</a>"
    },
    "source": {
        "contributors_enabled": False,
        "friends_count": 527,
        "notifications": None,
        "is_translation_enabled": False,
        "profile_background_image_url": "http://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png",
        "statuses_count": 2123,
        "profile_link_color": "2FC2EF",
        "protected": False,
        "utc_offset": -18000,
        "profile_sidebar_fill_color": "252429",
        "id": 24398192,
        "url": "http://chartsock.com",
        "profile_sidebar_border_color": "FFFFFF",
        "profile_background_image_url_https": "https://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png",
        "profile_image_url": "http://pbs.twimg.com/profile_images/526488583834587136/t8N0m0zW_normal.png",
        "profile_background_color": "1A1B1F",
        "listed_count": 12,
        "name": "~* christamas h *~",
        "created_at": "Sat Mar 14 17:20:57 +0000 2009",
        "description": u "(\u256f\u25e1 \u203f\u25e1)\u256f\ufe35 \u253b\u2501\u253b // #botALLY",
        "profile_background_tile": True,
        "following": None,
        "is_translator": False,
        "profile_location": None,
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/526488583834587136/t8N0m0zW_normal.png",
        "profile_use_background_image": True,
        "id_str": "24398192",
        "lang": "en",
        "location": "Los Angeles,
        CA ",
        "followers_count": 422,
        "time_zone": "Eastern Time (US & Canada)",
        "follow_request_sent": None,
        "geo_enabled": False,
        "profile_banner_url": "https://pbs.twimg.com/profile_banners/24398192/1393448193",
        "default_profile_image": False,
        "favourites_count": 981,
        "default_profile": False,
        "verified": False,
        "screen_name": "_hartsick",
        "profile_text_color": "666666"
    },
    "created_at": "Wed Dec 24 04:42:30 +0000 2014"
}
