{
    "target": {
        "contributors_enabled": False,
        "friends_count": 23,
        "notifications": False,
        "is_translation_enabled": False,
        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "statuses_count": 102,
        "profile_link_color": "0084B4",
        "protected": False,
        "utc_offset": None,
        "profile_sidebar_fill_color": "DDEEF6",
        "id": 2921127146,
        "url": None,
        "profile_sidebar_border_color": "C0DEED",
        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profile_image_url": "http://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
        "profile_background_color": "C0DEED",
        "listed_count": 6,
        "name": "emotisponge",
        "created_at": "Sun Dec 07 01:30:21 +0000 2014",
        "description": "i am human and i need 2b luved,
        just like everybdy
        else does // tweet 'help' for some tips,
        or 'status'
        for how i 'm feeling! // by @_hartsick. WARNING: BETA",
        "profile_background_tile": False,
        "following": False,
        "is_translator": False,
        "profile_location": None,
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
        "profile_use_background_image": True,
        "id_str": "2921127146",
        "lang": "en",
        "location": None,
        "followers_count": 21,
        "time_zone": None,
        "follow_request_sent": False,
        "geo_enabled": False,
        "profile_banner_url": "https://pbs.twimg.com/profile_banners/2921127146/1417916415",
        "default_profile_image": False,
        "favourites_count": 30,
        "default_profile": True,
        "verified": False,
        "screen_name": "emotisponge",
        "profile_text_color": "333333"
    },
    "event": "follow",
    "source": {
        "contributors_enabled": False,
        "friends_count": 963,
        "notifications": False,
        "is_translation_enabled": False,
        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme14/bg.gif",
        "statuses_count": 7138,
        "profile_link_color": "67777A",
        "protected": False,
        "utc_offset": 39600,
        "profile_sidebar_fill_color": "EFEFEF",
        "id": 194096921,
        "url": "http://t.co/VqJPccSaY9",
        "profile_sidebar_border_color": "FFFFFF",
        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme14/bg.gif",
        "profile_image_url": "http://pbs.twimg.com/profile_images/490681469681942529/iSLSUFHH_normal.png",
        "profile_background_color": "131516",
        "listed_count": 20,
        "name": u "\u141b",
        "created_at": "Thu Sep 23 12:34:18 +0000 2010",
        "description": "CSIT student, pianist/composer, alto, metalhead, learner of languages, cat person, proud bot parent",
        "profile_background_tile": True,
        "following": False,
        "is_translator": False,
        "profile_location": None,
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/490681469681942529/iSLSUFHH_normal.png",
        "profile_use_background_image": False,
        "id_str": "194096921",
        "lang": "en",
        "location": "Melbourne,
        Australia ",
        "followers_count": 367,
        "time_zone": "Melbourne",
        "follow_request_sent": False,
        "geo_enabled": False,
        "default_profile_image": False,
        "favourites_count": 4768,
        "default_profile": False,
        "verified": False,
        "screen_name": "dbaker_h",
        "profile_text_color": "333333"
    },
    "created_at": "Tue Dec 23 07:35:03 +0000 2014"
}
