{
    "target": {
        "follow_request_sent": False,
        "friends_count": 24,
        "notifications": False,
        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
        "statuses_count": 102,
        "profile_link_color": "0084B4",
        "protected": False,
        "utc_offset": None,
        "profile_sidebar_fill_color": "DDEEF6",
        "id": 2921127146,
        "url": None,
        "profile_sidebar_border_color": "C0DEED",
        "followers_count": 22,
        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
        "profile_banner_url": "https://pbs.twimg.com/profile_banners/2921127146/1417916415",
        "profile_background_color": "C0DEED",
        "listed_count": 5,
        "name": "emotisponge",
        "created_at": "Sun Dec 07 01:30:21 +0000 2014",
        "profile_background_tile": False,
        "profile_image_url": "http://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
        "following": True,
        "is_translator": False,
        "description": "i am human and i need 2b luved,
        just like everybdy
        else does // tweet 'help' for some tips,
        or 'status'
        for how i 'm feeling! // by @_hartsick. WARNING: BETA",
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/541407861335527424/S8znspEK_normal.png",
        "geo_enabled": False,
        "id_str": "2921127146",
        "lang": "en",
        "location": None,
        "contributors_enabled": False,
        "time_zone": None,
        "profile_use_background_image": True,
        "default_profile_image": False,
        "favourites_count": 30,
        "default_profile": True,
        "verified": False,
        "screen_name": "emotisponge",
        "profile_text_color": "333333"
    },
    "event": "list_member_removed",
    "target_object": {
        "following": False,
        "name": "hartbots",
        "id": 183747206,
        "description": "@_hartsick's legion of internet things",
        "slug": "hartbots",
        "uri": "/_hartsick/lists/hartbots",
        "mode": "public",
        "subscriber_count": 0,
        "user": {
            "follow_request_sent": False,
            "friends_count": 527,
            "notifications": False,
            "profile_background_image_url": "http://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png",
            "statuses_count": 2123,
            "profile_link_color": "2FC2EF",
            "protected": False,
            "utc_offset": -18000,
            "profile_sidebar_fill_color": "252429",
            "id": 24398192,
            "url": "http://chartsock.com",
            "profile_sidebar_border_color": "FFFFFF",
            "followers_count": 422,
            "profile_background_image_url_https": "https://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/24398192/1393448193",
            "profile_background_color": "1A1B1F",
            "listed_count": 12,
            "name": "~* christamas h *~",
            "created_at": "Sat Mar 14 17:20:57 +0000 2009",
            "profile_background_tile": True,
            "profile_image_url": "http://pbs.twimg.com/profile_images/526488583834587136/t8N0m0zW_normal.png",
            "following": False,
            "is_translator": False,
            "description": u "(\u256f\u25e1 \u203f\u25e1)\u256f\ufe35 \u253b\u2501\u253b                                 // #botALLY",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/526488583834587136/t8N0m0zW_normal.png",
            "geo_enabled": False,
            "id_str": "24398192",
            "lang": "en",
            "location": "Los Angeles,
            CA ",
            "contributors_enabled": False,
            "time_zone": "Eastern Time (US & Canada)",
            "profile_use_background_image": True,
            "default_profile_image": False,
            "favourites_count": 981,
            "default_profile": False,
            "verified": False,
            "screen_name": "_hartsick",
            "profile_text_color": "666666"
        },
        "created_at": "Tue Dec 02 17:30:01 +0000 2014",
        "member_count": 2,
        "id_str": "183747206",
        "full_name": "@_hartsick/lists/hartbots"
    },
    "source": {
        "follow_request_sent": False,
        "friends_count": 527,
        "notifications": False,
        "profile_background_image_url": "http://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png",
        "statuses_count": 2123,
        "profile_link_color": "2FC2EF",
        "protected": False,
        "utc_offset": -18000,
        "profile_sidebar_fill_color": "252429",
        "id": 24398192,
        "url": "http://chartsock.com",
        "profile_sidebar_border_color": "FFFFFF",
        "followers_count": 422,
        "profile_background_image_url_https": "https://pbs.twimg.com/profile_background_images/440644211373649920/DWLVh6RV.png",
        "profile_banner_url": "https://pbs.twimg.com/profile_banners/24398192/1393448193",
        "profile_background_color": "1A1B1F",
        "listed_count": 12,
        "name": "~* christamas h *~",
        "created_at": "Sat Mar 14 17:20:57 +0000 2009",
        "profile_background_tile": True,
        "profile_image_url": "http://pbs.twimg.com/profile_images/526488583834587136/t8N0m0zW_normal.png",
        "following": False,
        "is_translator": False,
        "description": u "(\u256f\u25e1 \u203f\u25e1)\u256f\ufe35 \u253b\u2501\u253b // #botALLY",
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/526488583834587136/t8N0m0zW_normal.png",
        "geo_enabled": False,
        "id_str": "24398192",
        "lang": "en",
        "location": "Los Angeles,
        CA ",
        "contributors_enabled": False,
        "time_zone": "Eastern Time (US & Canada)",
        "profile_use_background_image": True,
        "default_profile_image": False,
        "favourites_count": 981,
        "default_profile": False,
        "verified": False,
        "screen_name": "_hartsick",
        "profile_text_color": "666666"
    },
    "created_at": "Wed Dec 24 04:48:13 +0000 2014"
}
